title = "Christopher G. Mcintyre"
description = """
Christopher G. McIntyre's Personal Website
"""
base_url = "https://cgmcintyre.com"
compile_sass = true
highlight_code = true
generate_rss = true
highlight_theme = "ir-white"

[[taxonomies]]
	name = "tags"
	rss = true
